ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  ACTION_SPACE_CONFIG: "v1"
  SCENE: 'data/citi.glb'
  HABITAT_SIM_V0:
    ALLOW_SLIDING: false
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
#    HFOV: 69
    HFOV: 56
    ORIENTATION: [-0.1,0,0]
    POSITION: [-0.015, 0.589, 0.047]
  DEPTH_SENSOR:
#    TYPE: "RealisticHabitatSimDepthSensor"
    WIDTH: 256
    HEIGHT: 256
#    HFOV: 90
    HFOV: 80
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    NORMALIZE: true
    POSITION: [0.000, 0.589, 0.047]
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
    HEIGHT: 0.65
    RADIUS: 0.18
    ACTION_SPACE_CONFIG: "v1"