ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ACTION_SPACE_CONFIG: "v1"
SIMULATOR:
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 1.5
    RADIUS: 0.3
    ACTION_SPACE_CONFIG: "v1"
  HABITAT_SIM_V0:
    ACTION_SPACE_CONFIG: "v1"
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    POSITION: [0, 0.8, 0]
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    POSITION: [0, 0.8, 0]
    WIDTH: 256
    HEIGHT: 256
    NORMALIZE_DEPTH: True
  SCENE: 'data/citi.glb'
ACTION_SPACE_CONFIG: "v1"
